In [1]:
import Pkg; Pkg.activate(joinpath(@__DIR__,"..")); Pkg.instantiate();
using LinearAlgebra
using ForwardDiff
using Test
include(joinpath(@__DIR__,"utils.jl"))

  Activating environment at `~/devel/optimal_control/HW0/Project.toml`
Precompiling project...
  ✓ HW0
  1 dependency successfully precompiled in 2 seconds (141 already precompiled)


matrix_isapprox (generic function with 1 method)

# Question 1: Automatic Differentiation in Julia (7 pts)
Julia has a fast and easy to use forward-mode automatic differentiation package called [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl) that we will make use of throughout this course. In general it is easy to use and very fast, but there are a few quirks that are detailed below. This notebook will start by walking through general usage for the following cases:
- functions with a single input 
- functions with multiple inputs
- composite functions

as well as a guide on how to avoid the most common ForwardDiff.jl error caused by creating arrays inside the function being differentiated. First, let's look at the ForwardDiff.jl functions that we are going to use:
- `derivative(f,x)` derivative of scalar or vector valued f wrt scalar x 
- `jacobian(f,x)` jacobian of vector valued f wrt vector x
- `gradient(f,x)` gradient of scalar valued f wrt vector x 
- `hessian(f,x)` hessian of scalar valued f wrt vector x 

### Note on gradients:
For an arbitrary function $f(x):\mathbb{R}^N \rightarrow \mathbb{R}^M$, the jacobian is the following:


$$\frac{\partial f(x)}{\partial x} = \left[\begin{array}{ccc}
\frac{\partial f_{1}}{\partial x_{1}} & \cdots & \frac{\partial f_{1}}{\partial x_{n}} \\
\vdots & \ddots & \vdots \\
\frac{\partial f_{m}}{\partial x_{1}} & \cdots & \frac{\partial f_{m}}{\partial x_{n}}
\end{array}\right] $$


Now if we have a scalar valued function (like a cost function) $f(x):\mathbb{R}^N \rightarrow \mathbb{R}$, the jacobian is the following row vector:

$$\frac{\partial f(x)}{\partial x} = \left[\begin{array}{ccc}
\frac{\partial f_{1}}{\partial x_{1}} & \cdots & \frac{\partial f_{1}}{\partial x_{n}}
\end{array}\right] $$

The transpose of this jacobian for scalar valued functions is called the gradient:

$$ \nabla f(x) = \bigg[\frac{\partial f(x)}{\partial x}\bigg]^T $$

TLDR:
- the jacobian of a scalar value function is a row vector 
- the gradient is the transpose of this jacobian, making the gradient a column vector 
- ForwardDiff.jl will give you an error if you try to take a jacobian of a scalar valued function, use the gradient function instead

## Part (a): General usage (2 pts)
The API for functions with one input is detailed below:

In [2]:
# NOTE: this block is a tutorial, you do not have to fill anything out. 

function foo1(x)
    #scalar input, scalar output
    return sin(x)*cos(x)^2
end

function foo2(x)
    # vector input, scalar output
    return sin(x[1]) + cos(x[2])
end
function foo3(x)
    # vector input, vector output
    return [sin(x[1])*x[2];cos(x[2])*x[1]]
end


let # we just use this to avoid creating global variables
    
    # evaluate the derivative of foo1 at x1
    x1 = 5*randn();
    @show ∂foo1_∂x = ForwardDiff.derivative(foo1, x1);
    
    # evaluate the gradient and hessian of foo2 at x2
    x2 = 5*randn(2);
    @show ∇foo2 = ForwardDiff.gradient(foo2, x2);
    @show ∇²foo2 = ForwardDiff.hessian(foo2, x2);
    
    # evluate the jacobian of foo3 at x2
    @show ∂foo3_∂x = ForwardDiff.jacobian(foo3,x2);
    
end

∂foo1_∂x = ForwardDiff.derivative(foo1, x1) = -0.6270589074319141
∇foo2 = ForwardDiff.gradient(foo2, x2) = [-0.6503171938696883, -0.04157896909407759]
∇²foo2 = ForwardDiff.hessian(foo2, x2) = [-0.7596627852919046 -0.0; -0.0 -0.9991352207429551]
∂foo3_∂x = ForwardDiff.jacobian(foo3, x2) = [4.059016121920946 0.7596627852919046; 0.9991352207429551 -0.09475008136623124]


2×2 Matrix{Float64}:
 4.05902    0.759663
 0.999135  -0.0947501

In [3]:
# here is our function of interest
function foo4(x)
    Q = diagm([1;2;3.0])
    return 0.5*x'*Q*x/x[1] - log(x[1])*exp(x[2])^x[3] 
end

function foo4_expansion(x)
    # TODO: this function should output the hessian H and gradient g of the function foo4
    
    # TODO: calculate the gradient of foo4 evaluated at x
    g = zeros(length(x))
    
    # TODO: calculate the hessian of foo4 evaluated at x
    H = zeros(length(x),length(x))
    
    return g, H
end

foo4_expansion (generic function with 1 method)

In [4]:
@testset "1a" begin                        # POINTS = 2
    x = [.2;.4;.5]
    g,H = foo4_expansion(x)
    @test isapprox(g,[-18.98201379080085, 4.982885952667278, 8.286308762133823],atol = 1e-8)        # POINTS = 1
    @test matrix_isapprox(H,[164.2850689540042 -23.053506895400425 -39.942805516320334; -23.053506895400425 10.491442976333639 2.3589262864014673; -39.94280551632034 2.3589262864014673 15.314523504853529];atol = 1e-8) # POINTS = 1
end

1a: Test Failed at In[4]:4
  Expression: isapprox(g, [-18.98201379080085, 4.982885952667278, 8.286308762133823], atol = 1.0e-8)
   Evaluated: isapprox([0.0, 0.0, 0.0], [-18.98201379080085, 4.982885952667278, 8.286308762133823]; atol = 1.0e-8)
Stacktrace:
 [1] macro expansion
   @ In[4]:4 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ In[4]:2
1a: Test Failed at In[4]:5
  Expression: matrix_isapprox(H, [164.2850689540042 -23.053506895400425 -39.942805516320334; -23.053506895400425 10.491442976333639 2.3589262864014673; -39.94280551632034 2.3589262864014673 15.314523504853529]; atol = 1.0e-8)
Stacktrace:
 [1] macro expansion
   @ In[4]:5 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ In[4]:2
Test Summary: | Fail  Total
1a            |    2  

LoadError: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.

## Part (b): Derivatives for functions with multiple input arguments (2 pts)

In [5]:
# NOTE: this block is a tutorial, you do not have to fill anything out. 

# calculate derivatives for functions with multiple inputs 
function dynamics(x,a,b,c)
    return [x[1]*a; b*c*x[2]*x[1]]
end

let 
    x1 = randn(2)
    a = randn()
    b = randn()
    c = randn()
    
    # this evaluates the jacobian with respect to x, given a, b, and c
    A = ForwardDiff.jacobian(dx -> dynamics(dx, a, b, c), x1)
end

2×2 Matrix{Float64}:
 -1.13397   -0.0
  0.261609  -0.0280676

In [6]:
function eulers(x,u,J)
    # dynamics when x is angular velocity and u is an input torque
    ẋ = J\(u - cross(x,J*x))
    return ẋ
end

function eulers_jacobians(x,u,J)
    # given x, u, and J, calculate the following two jacobians 
    
    # TODO: fill in the following two jacobians
    
    # ∂ẋ/∂x
    A = zeros(3,3)
    
    # ∂ẋ/∂u
    B = zeros(3,3)
    
    return A, B
end

eulers_jacobians (generic function with 1 method)

In [7]:
@testset "1b" begin                                                # POINTS = 2
    
    x = [.2;-7;.2]
    u = [.1;-.2;.343]
    J = diagm([1.03;4;3.45])
    
    A,B = eulers_jacobians(x,u,J)

    @test isapprox(A,-J\(skew(x)*J - skew(J*x)), atol = 1e-8)  # POINTS = 1 

    @test matrix_isapprox(B,inv(J),atol = 1e-8)                # POINTS = 1 

end

1b: Test Failed at In[7]:9
  Expression: isapprox(A, -J \ (skew(x) * J - skew(J * x)), atol = 1.0e-8)
   Evaluated: isapprox([0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0], [-0.0 0.10679611650485435 -3.737864077669901; 0.12100000000000001 -0.0 0.12100000000000001; 6.0260869565217385 -0.1721739130434783 -0.0]; atol = 1.0e-8)
Stacktrace:
 [1] macro expansion
   @ In[7]:9 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ In[7]:3
1b: Test Failed at In[7]:11
  Expression: matrix_isapprox(B, inv(J), atol = 1.0e-8)
Stacktrace:
 [1] macro expansion
   @ In[7]:11 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ In[7]:3
Test Summary: | Fail  Total
1b            |    2      2


LoadError: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.

## Part (c): Derivatives of composite functions (1 pts)

In [8]:
# NOTE: this block is a tutorial, you do not have to fill anything out. 
function f(x)
    return x[1]*x[2]
end
function g(x)
    return [x[1]^2; x[2]^3]
end

let 
    x1 = 2*randn(2)
    
    # using gradient of the composite function
    ∇f_1 = ForwardDiff.gradient(dx -> f(g(dx)), x1)
    
    # using the chain rule 
    J = ForwardDiff.jacobian(g, x1)
    ∇f_2 = J'*ForwardDiff.gradient(f, g(x1))
    
    @show norm(∇f_1 - ∇f_2)
end

norm(∇f_1 - ∇f_2) = 0.0


0.0

In [9]:
function f2(x)
    return x*sin(x)/2
end
function g2(x)
    return cos(x)^2 - tan(x)^3
end

function composite_derivs(x)
    
    # TODO: return ∂y/∂x where y = g2(f2(x)) 
    # (hint: this is 1D input and 1D output, so it's ForwardDiff.derivative)
    return NaN
end    

composite_derivs (generic function with 1 method)

In [10]:
@testset "1c" begin                                           # POINTS = 1
    x = 1.34 
    deriv = composite_derivs(x)

    @test isapprox(deriv,-2.390628273373545,atol = 1e-8)  # POINTS = 1
end

1c: Test Failed at In[10]:5
  Expression: isapprox(deriv, -2.390628273373545, atol = 1.0e-8)
   Evaluated: isapprox(NaN, -2.390628273373545; atol = 1.0e-8)
Stacktrace:
 [1] macro expansion
   @ In[10]:5 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ In[10]:2
Test Summary: | Fail  Total
1c            |    1      1


LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.

## Part (d): Fixing the most common ForwardDiff error (2 pt)
First we will show an example of this error:

In [11]:
# NOTE: this block is a tutorial, you do not have to fill anything out. 
function f_zero_1(x)
    
    # diffing through this function will error on this line 
    xdot = zeros(length(x))
    
    xdot[1] = x[1]*x[2]
    xdot[2] = x[2]^2
    
    return xdot 
end

let 
    # try and calculate the jacobian of f_zero_1 on x1
    x1 = randn(2)
    @info "this error is expected:"
    try 
        ForwardDiff.jacobian(f_zero_1,x1)
    catch e 
        buf = IOBuffer()
        showerror(buf,e)
        message = String(take!(buf))
        Base.showerror(stdout,e)
    end
end

┌ Info: this error is expected:
└ @ Main In[11]:16


MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(f_zero_1), Float64}, Float64, 2})
Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  (::Type{T})(::T) where T<:Number at boot.jl:760
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  ...

This is the most common ForwardDiff error that you will encounter. ForwardDiff works by pushing `ForwardDiff.Dual` variables through the function being differentiated. Normally this works without issue, but if you create a vector of `Float64` (like you would with `xdot = zeros(5)`, it is unable to fit the `ForwardDiff.Dual`'s in with the `Float64`'s. To get around this, you have two options:

### Option 1 
Our first option is just creating xdot directly, without creating an array of zeros to index into. 

In [12]:
# NOTE: this block is a tutorial, you do not have to fill anything out. 
function f_zero_1(x)
    
    # let's create xdot directly, without first making a vector of zeros 
    xdot = [x[1]*x[2], x[2]^2]
    
    # NOTE: the compiler figures out which type to make xdot, so when you call the function normally
    # it's a Float64, and when it's being diffed, it's automatically promoted to a ForwardDiff.Dual type

    return xdot 
end

let 
    # try and calculate the jacobian of f_zero_1 on x1
    x1 = randn(2)
    ForwardDiff.jacobian(f_zero_1,x1) # this will work
end

2×2 Matrix{Float64}:
 1.1094  0.445534
 0.0     2.2188

### Option 2
The second option is to create the array of zeros in a way that accounts for the input type. This can be done by replacing `zeros(length(x))` with `zeros(eltype(x),length(x))`. The first argument `eltype(x)` simply creates a vector of zeros that is the same type as the element type in vector x. 

In [13]:
# NOTE: this block is a tutorial, you do not have to fill anything out. 
function f_zero_1(x)
    
    # diffing through this function will error on this line 
    xdot = zeros(eltype(x), length(x))
    
    xdot[1] = x[1]*x[2]
    xdot[2] = x[2]^2
    
    return xdot 
end

let 
    # try and calculate the jacobian of f_zero_1 on x1
    x1 = randn(2)
    ForwardDiff.jacobian(f_zero_1,x1) # this will fail! 
end

2×2 Matrix{Float64}:
 0.475363  -0.384079
 0.0        0.950725

Now you can show that you understand these two options by fixing two broken functions.

In [14]:
# TODO: fix this error when trying to diff through this function
# hint: you can use eltype([x;u]) to return the correct type if either x or u is a ForwardDiff.Dual (option 1)

function dynamics(x,u)
    ẋ = zeros(length(x))
    ẋ[1] = x[1]*sin(u[1])
    ẋ[2] = x[2]*cos(u[2])
    return ẋ
end

dynamics (generic function with 2 methods)

In [15]:
@testset "1d" begin                                     # POINTS = 2
    x = [.1;.4]
    u = [.2;-.3]
    A = ForwardDiff.jacobian(_x -> dynamics(_x,u),x) 
    B = ForwardDiff.jacobian(_u -> dynamics(x,_u),u) 
    @test typeof(A) == Matrix{Float64}                  # POINTS = 1
    @test typeof(B) == Matrix{Float64}                  # POINTS = 1
end

1d: Error During Test at In[15]:1
  Got exception outside of a @test
  MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{var"#6#8"{Vector{Float64}}, Float64}, Float64, 2})
  Closest candidates are:
    (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
    (::Type{T})(::T) where T<:Number at boot.jl:760
    (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
    ...
  Stacktrace:
    [1] convert(#unused#::Type{Float64}, x::ForwardDiff.Dual{ForwardDiff.Tag{var"#6#8"{Vector{Float64}}, Float64}, Float64, 2})
      @ Base ./number.jl:7
    [2] setindex!(A::Vector{Float64}, x::ForwardDiff.Dual{ForwardDiff.Tag{var"#6#8"{Vector{Float64}}, Float64}, Float64, 2}, i1::Int64)
      @ Base ./array.jl:843
    [3] dynamics(x::Vector{ForwardDiff.Dual{ForwardDiff.Tag{var"#6#8"{Vector{Float64}}, Float64}, Float64, 2}}, u::Vector{Float64})
      @ Main ./In[14]:6
    [4] (::var"#6#8"{Vector{Float64}})(_x::Vector{ForwardDiff.D

LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.